### ISSUE TITLE
split up firestore_api in _api with platform channels and _annotations

### ISSUE THREAD

**Issue by lukas-h** [dartclub/firestore_dart#17]
- [ ] New package structure with platform interfaces
    https://flutter.dev/docs/development/packages-and-plugins/developing-packages#plugin
```
flutter:
  plugin:
    platforms:
      android:
        package: bla
        pluginClass: bla
      ios:
        pluginClass: bla
      web:
        default_package: bla 
      macos:
        default_package: bla
```

- [ ] Separate package for annotations, that needs to be included as dev_dependency when using
